### PR TITLE
Fix build error due to base image

### LINKED ISSUE #11: docker build -t ppiper/xs-cli --build-arg XSZIP=XS_CLIENT00_128-70002340.ZIP . throws error
docker build -t ppiper/xs-cli --build-arg XSZIP=XS_CLIENT00_128-70002340.ZIP .

ERROR: failed to solve: process "/bin/sh -c apt-get update &&     apt-get install --yes --no-install-recommends procps unzip &&     rm -rf /var/lib/apt/lists/* &&     addgroup -gid 1000 piper &&     useradd piper --uid 1000 --gid 1000 --shell /bin/bash --create-home &&   
  mkdir --parents ${XSCLI} &&     unzip -d ${XSCLI} /tmp/${XSZIP} &&     rm --recursive --force /tmp/${XSZIP} &&     chown --recursive piper:piper ${XSCLI}" did not complete successfully: exit code: 100

Complete log:

[+] Building 2.8s (2/3)
 => [internal] load build definition from Dockerfile                                                                               0.2s 
[+] Building 24.1s (7/8)
 => [internal] load build definition from Dockerfile                                                                               0.2s 
 => => transferring dockerfile: 769B                                                                                               0.0s 
 => [internal] load .dockerignore                                                                                                  0.3s 
 => => transferring context: 2B                                                                                                    0.0s 
 => [internal] load metadata for docker.io/library/buildpack-deps:stretch-curl                                                     3.9s 
 => [internal] load build context                                                                                                  1.6s 
 => => transferring context: 96.02MB                                                                                               1.5s 
 => CACHED [1/4] FROM docker.io/library/buildpack-deps:stretch-curl@sha256:f58e38c7a4fa582d6d858469b8ae2f346b46f70151aab61e64c6f0  0.0s 
 => [2/4] COPY XS_CLIENT00_128-70002340.ZIP /tmp/XS_CLIENT00_128-70002340.ZIP                                                     11.5s 
 => ERROR [3/4] RUN apt-get update &&     apt-get install --yes --no-install-recommends procps unzip &&     rm -rf /var/lib/apt/l  6.7s 
------
 > [3/4] RUN apt-get update &&     apt-get install --yes --no-install-recommends procps unzip &&     rm -rf /var/lib/apt/lists/* &&     
addgroup -gid 1000 piper &&     useradd piper --uid 1000 --gid 1000 --shell /bin/bash --create-home &&     mkdir --parents /opt/sap/xs-cli &&     unzip -d /opt/sap/xs-cli /tmp/XS_CLIENT00_128-70002340.ZIP &&     rm --recursive --force /tmp/XS_CLIENT00_128-70002340.ZIP && 
    chown --recursive piper:piper /opt/sap/xs-cli:
#0 1.785 Ign:1 http://security.debian.org/debian-security stretch/updates InRelease
#0 1.799 Ign:2 http://deb.debian.org/debian stretch InRelease
#0 1.935 Ign:3 http://security.debian.org/debian-security stretch/updates Release
#0 1.938 Ign:4 http://deb.debian.org/debian stretch-updates InRelease
#0 2.090 Ign:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 2.097 Ign:6 http://deb.debian.org/debian stretch Release
#0 2.247 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 2.267 Ign:8 http://deb.debian.org/debian stretch-updates Release
#0 2.484 Ign:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 2.540 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#0 2.652 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 2.662 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#0 2.812 Ign:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 2.862 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#0 2.976 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 3.094 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 3.128 Ign:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 3.233 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#0 3.265 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 3.381 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#0 3.386 Ign:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 3.564 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#0 3.584 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 3.704 Err:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 3.704   404  Not Found
#0 3.863 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 3.946 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 4.138 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#0 4.357 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#0 4.510 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#0 4.785 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 4.933 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#0 5.075 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#0 5.212 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#0 5.354 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 5.488 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#0 5.640 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#0 5.788 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#0 5.965 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 6.104 Err:9 http://deb.debian.org/debian stretch/main amd64 Packages
#0 6.104   404  Not Found
#0 6.221 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#0 6.323 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#0 6.480 Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 6.480   404  Not Found
#0 6.509 Reading package lists...
#0 6.568 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#0 6.568 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#0 6.568 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#0 6.568 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found 
#0 6.568 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
#0 6.568 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
#0 6.568 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
Dockerfile:11
--------------------
  10 |     # ps needs to be available to be able to be used in docker.inside, see https://issues.jenkins-ci.org/browse/JENKINS-40101    
  11 | >>> RUN apt-get update && \
  12 | >>>     apt-get install --yes --no-install-recommends procps unzip && \
  13 | >>>     rm -rf /var/lib/apt/lists/* && \
  14 | >>>     addgroup -gid 1000 piper && \
  15 | >>>     useradd piper --uid 1000 --gid 1000 --shell /bin/bash --create-home && \
  16 | >>>     mkdir --parents ${XSCLI} && \
  17 | >>>     unzip -d ${XSCLI} /tmp/${XSZIP} && \
  18 | >>>     rm --recursive --force /tmp/${XSZIP} && \
  19 | >>>     chown --recursive piper:piper ${XSCLI}
  20 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update &&     apt-get install --yes --no-install-recommends procps unzip &&     rm -rf /var/lib/apt/lists/* &&     addgroup -gid 1000 piper &&     useradd piper --uid 1000 --gid 1000 --shell /bin/bash --create-home &&   
  mkdir --parents ${XSCLI} &&     unzip -d ${XSCLI} /tmp/${XSZIP} &&     rm --recursive --force /tmp/${XSZIP} &&     chown --recursive piper:piper ${XSCLI}" did not complete successfully: exit code: 100

### PR DESCRIPTION
**Pull request by remi-sap**
apt update fails with this base image.

Fix #11

### CODE REVIEW

**Comment by remi-sap** [comment]
Reproducing the error is quite easy:

```shell

docker run -ti buildpack-deps:stretch-curl /bin/bash

root@39368575de11:/# apt update
Ign:1 http://deb.debian.org/debian stretch InRelease
Ign:2 http://security.debian.org/debian-security stretch/updates InRelease
Ign:3 http://deb.debian.org/debian stretch-updates InRelease
Err:4 http://security.debian.org/debian-security stretch/updates Release
  404  Not Found
Err:5 http://deb.debian.org/debian stretch Release
  404  Not Found
Err:6 http://deb.debian.org/debian stretch-updates Release
  404  Not Found
Reading package lists... Done
E: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@39368575de11:/# echo $?
100

```
So the build fails at `apt update`

**Comment by kaylinche** [comment]
Thank you @remi-sap for the PR. I wonder why you had to add the mbt tool, because the build and execution will work with an adapted base image URL only.

**Comment by remi-sap** [comment]
> Thank you @remi-sap for the PR. I wonder why you had to add the mbt tool, because the build and execution will work with an adapted base image URL only.

The popular scenario is to build an mbt from source files then publish it in XSA. Adding MBT simplifies this scenario.  Maybe this should be split into another change?

**Comment by kaylinche** [comment]
> > Thank you @remi-sap for the PR. I wonder why you had to add the mbt tool, because the build and execution will work with an adapted base image URL only.
> 
> The popular scenario is to build an mbt from source files then publish it in XSA. Adding MBT simplifies this scenario. Maybe this should be split into another change?

Due to the fact that the image build description is intended to be used with one [particular Piper scenario](https://www.project-piper.io/scenarios/xsa-deploy/Readme/), the mbt part is not the focus of the image itself and shouldn't be added at all.

**Comment by remi-sap** [comment]
Fixed by PR #14

**Pull request closed without merging**
